<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
JHtml::_('behavior.caption');

function getCatId() {
  //Modified from: http://stackoverflow.com/questions/8928967/joomla-display-catagory-name-in-template

  $db = JFactory::getDBO();
  $id = JRequest::getString('id');
  $view = JRequest::getString('view');
  $catid = NULL;

  if ($view == 'article') {
    $sql = "SELECT catid FROM #__content WHERE #__content.id = $id";
    $db->setQuery($sql);
    $catid = $db->loadResult();
  }
  elseif ($view == 'category') {
    $catid = $id;
  }
  return $catid;
}


?>
<!-- the div below is generated by template starlink & com_content/category/mainblog  override -->
<div class="blog<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Blog">
  <div class="container">
  <?php if ($this->params->get('show_page_heading')) : ?>
    <h1 class="block__header col-xs-12 col-md-9"> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
  <?php endif; ?>

  <?php if ($this->params->get('show_category_title', 1) or $this->params->get('page_subheading')) : ?>
    <h2> <?php echo $this->escape($this->params->get('page_subheading')); ?>
      <?php if ($this->params->get('show_category_title')) : ?>
        <span class="subheading-category"><?php echo $this->category->title; ?></span>
      <?php endif; ?>
    </h2>
  <?php endif; ?>

  <?php if ($this->params->get('show_cat_tags', 1) && !empty($this->category->tags->itemTags)) : ?>
    <?php $this->category->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
    <?php echo $this->category->tagLayout->render($this->category->tags->itemTags); ?>
  <?php endif; ?>

  <?php if ($this->params->get('show_description', 1) || $this->params->def('show_description_image', 1)) : ?>
    <div class="category-desc clearfix">
      <?php if ($this->params->get('show_description_image') && $this->category->getParams()->get('image')) : ?>
        <img src="<?php echo $this->category->getParams()->get('image'); ?>" alt="<?php echo htmlspecialchars($this->category->getParams()->get('image_alt')); ?>"/>
      <?php endif; ?>
      <?php if ($this->params->get('show_description') && $this->category->description) : ?>
        <?php echo JHtml::_('content.prepare', $this->category->description, '', 'com_content.category'); ?>
      <?php endif; ?>
    </div>
  <?php endif; ?>

  <?php if (empty($this->lead_items) && empty($this->link_items) && empty($this->intro_items)) : ?>
    <?php if ($this->params->get('show_no_articles', 1)) : ?>
      <p><?php echo JText::_('COM_CONTENT_NO_ARTICLES'); ?></p>
    <?php endif; ?>
  <?php endif; ?>

  <?php $leadingcount = 0; ?>
  <?php if (!empty($this->lead_items)) : ?>
    <div class="row">
      <?php
      jimport( 'joomla.application.module.helper' );
      if(count(JModuleHelper::getModules('sBlog-rightSideMenu'))) {
        $cols = "col-md-9";
      } else {
        $cols = "col-md-12";
      } ?>
      <section class="col-xs-12 <?=$cols?> items-leading clearfix">
        <?php foreach ($this->lead_items as &$item) : ?>
          <div class="leading-<?php echo $leadingcount; ?><?php echo $item->state == 0 ? ' system-unpublished' : null; ?>"
               itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
            <?php
            $this->item = & $item;
            echo $this->loadTemplate('item');
            ?>
          </div>
          <?php $leadingcount++; ?>
        <?php endforeach; ?>
      </section><!-- end items-leading -->
      <?php if (count(JModuleHelper::getModules('sBlog-rightSideMenu'))) : ?>
      <aside class="hidden-xs hidden-sm col-md-3 panelBlog">
        <?php
          $modules = JModuleHelper::getModules( 'sBlog-rightSideMenu' );
          $attribs['style'] = 'xhtml';
          foreach ($modules AS $module ) {
            echo JModuleHelper::renderModule( $module, $attribs );
          }
        ?>
      </aside>
      <?php endif; ?>
    </div>
  <?php endif; ?>

  <?php
  $introcount = (count($this->intro_items));
  $counter = 0;
  ?>

  <?php if (!empty($this->intro_items)) : ?>
    <?php foreach ($this->intro_items as $key => &$item) : ?>
      <?php $rowcount = ((int) $key % (int) $this->columns) + 1; ?>
      <?php if ($rowcount == 1) : ?>
        <?php $row = $counter / $this->columns; ?>
        <section class="col-xs-12 col-sm-6 col-md-4">
      <?php endif; ?>
        <div class="article article--box <?php echo $item->state == 0 ? ' system-unpublished' : null; ?>"
             itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
          <?php
          $this->item = & $item;
          echo $this->loadTemplate('item');
          ?>
        </div>
        <!-- end div.item -->
        <?php $counter++; ?>
      <!-- end div.span -->
      <?php if (($rowcount == $this->columns) or ($counter == $introcount)) : ?>
        </section>
        <!-- end row -->
      <?php endif; ?>
    <?php endforeach; ?>
  <?php endif; ?>

  <?php if (!empty($this->link_items)) : ?>
    <div class="items-more">
      <?php echo $this->loadTemplate('links'); ?>
    </div>
  <?php endif; ?>

  <?php if (!empty($this->children[$this->category->id]) && $this->maxLevel != 0) : ?>
    <div class="cat-children">
      <?php if ($this->params->get('show_category_heading_title_text', 1) == 1) : ?>
        <h3> <?php echo JText::_('JGLOBAL_SUBCATEGORIES'); ?> </h3>
      <?php endif; ?>
      <?php echo $this->loadTemplate('children'); ?>
    </div>
  <?php endif; ?>

  <?php if (($this->params->def('show_pagination', 1) == 1 || ($this->params->get('show_pagination') == 2)) && ($this->pagination->get('pages.total') > 1)) : ?>
    <div class="row">
      <div class="col-xs-12">
        <nav class="pagination col-xs-12 col-md-9">
        <?php if ($this->params->def('show_pagination_results', 1)) : ?>
          <p class="counter pull-right"> <?php echo $this->pagination->getPagesCounter(); ?> </p>
        <?php endif; ?>
        <?php echo $this->pagination->getPagesLinks(); ?>
        </nav>
      </div>
    </div>
  <?php endif; ?>

  <?php
  $catid=getCatId();
  echo '<!-- catid= ' . $catid . ' -->' ;
  ?>
  </div>
</div>
