<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_articles_news
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
$item_heading = $params->get('item_heading', 'h4');
?>
<!-- the div below is generated by starlink & mod_article_news/default module override -->

<!--<pre><?php /*var_dump($params); */?></pre>-->
<div class="container<?php echo $moduleclass_sfx; ?>">
  <div class="row">
    <?php
      $i = 0;
      foreach ($list as $item) :
        if ( $i < count($list)-1 ) :  ?>
          <div class="col-xs-12 col-sm-6 col-md-4 clearfix">
        <?php else : ?>
          <div class="col-xs-12 col-sm-12 col-md-4 clearfix">
        <?php endif;
        require JModuleHelper::getLayoutPath('mod_articles_news', '_item');
        echo '</div>';
        $i++;
      endforeach;
    ?>
  </div>

<!--  <div class="showAllNews">
    <a href="<?=JUri::base()?>/index.php?Itemid=114">Смотреть остальные новости</a>
  </div>-->
</div>
